### ISSUE TITLE
Error while creating a new meme in chapter 6

### ISSUE THREAD

**Issue by One-cy** [oceanByte/near-academy-contracts#3]
I'm not sure were to report this.
I was learning the tutorial at NEAR Academy and I was completing chapter 6 (**https://near.academy/near101/chapter-6**) when I tried this command in my terminal:

`near call museum.testnet add_meme '{"meme" : "testingmemeregistration", "title" : "god", "data" : "https://9gag.com/gag/ad8K0vj", "category" : 4}' --accountId YES_I_Changed_THIS.testnet --amount 3`

And this is what I got:

"Scheduling a call: museum.testnet.add_meme({meme : testingmemeregistration, title : god, data : https://9gag.com/gag/ad8K0vj, category : 4}) with attached 3 NEAR
An error occured
SyntaxError: Unexpected token m in JSON at position 1
    at JSON.parse (<anonymous>)
    at scheduleFunctionCall (C:\Users\name\AppData\Roaming\npm\node_modules\near-cli\commands\call.js:54:84)
    at async Object.handler (C:\...\near-cli\utils\exit-on-error.js:52:9)
SyntaxError: Unexpected token m in JSON at position 1
    at JSON.parse (<anonymous>)
    at scheduleFunctionCall (C:\...\near-cli\commands\call.js:54:84)
    at async Object.handler (C:\Users\...\near-cli\utils\exit-on-error.js:52:9)"

What's happening?

**Comment by MeMent0L** [comment]
Hi there, thank you for raising the point. I'm not sure what is the problem; that's something that @amgando or @oceanByte can advise who to ask
